.MODEL SMALL
.STACK 100H
.DATA
VAR1 DB 0   ;WE ARE CREATING A BYTE VARIABLE WHOSE INITIAL VALUE IS 0
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    MOV AH,1
    INT 21H     ; STORED IN AL REGISTER
    MOV VAR1,AL
    
    MOV AH,2
    MOV DL,0AH  ; 0AH = NEWLINE
    INT 21H
    MOV DL,0DH  ; 0DH = CARRIAGE RETURN
    INT 21H
 
    MOV AH,2
    MOV DL,VAR1
    INT 21H
    
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN